vim9script

# Console default variables.

# TODO: find a way to control the spawn of terminal window.
# Control the spawn of the terminal window.
# -----------------------------------------------------------------
# Valid values are:
#   - "top"      open the terminal window in split on the top.
#   - "below"    open the terminal window in split on the bottom.
#   - "right"    open the terminal window in split on the right.
#   - "left"     open the terminal window in split on the left.
#   - "tab"      open the terminal window on a new tab.
g:console_open_position = "below"

# Adjust the height of the terminal window.  This option is ignored
# if the "g:console_open_position" is set to "tab".
# -----------------------------------------------------------------
# Valid value are: [15-80].
g:console_open_height = 20

def Console_control_height(): number
	if g:console_open_height < 15
		return 15
	elseif g:console_open_height > 80
		return 80
	else
		return g:console_open_height
	endif
enddef

# Open terminal window below the current window with the default
# shell. This function returns the buffer number of the terminal
# window generated by term_start().
def g:Console_open(): number
	var height: number = winheight(0) * Console_control_height() / 100
	
	below return term_start(&shell, {
		'term_name': ' Console ',
		'term_rows': height,
		'term_kill': 'kill',
		'term_finish': 'close',
		'norestore': 1,
	})
enddef

# Open terminal window and run commands on the new tab. The window
# will not close automatically after the executions is finished.
def g:Console_run(): number
	var cmds: string = input('run: ', '', 'shellcmd')
	if cmds != ""
		tab return term_start([
				&shell,
				&shellcmdflag,
				cmds
			], {
				'term_name': ' Run ',
				'term_kill': 'int',
				'term_finish': 'open',
				'norestore': 1,
		})
	else
		echow "Nothing is executed!"
		return 0
	endif
enddef

# vim:ft=vim:sw=2:ts=2
