vim9script

# Open terminal window below the current window with the default
# shell. This function returns the buffer number of the terminal
# window generated by term_start().
def g:Console_open(percent: number): number
	var pheight: number = 0
	
	if percent <= 15
		pheight = 15
	elseif percent >= 80
		pheight = 80
	else
		pheight = percent
	endif
	
	var height: number = winheight(0) * pheight / 100
	
	below return term_start(&shell, {
		'term_name': ' Console ',
		'term_rows': height,
		'term_kill': 'kill',
		'term_finish': 'close',
		'norestore': 1,
	})
enddef

# Open terminal window and run commands on the new tab. The window
# will not close automatically after the executions is finished.
def g:Console_run(): number
	var cmds: string = input('run: ', '', 'shellcmd')
	if cmds != ""
		tab return term_start(cmds, {
			'term_name': ' Run ',
			'term_kill': 'int',
			'term_finish': 'open',
			'norestore': 1,
		})
	else
		echo "Nothing is executed!"
		return 0
	endif
enddef

nnoremap ,0 :call g:Console_run()<cr>
# vim:ft=vim:sw=2:ts=2
